___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!

#### 1. Import NumPy Library

In [ ]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list = np.array([5,10,15,20,25])
my_list

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:
np.ones((4,4),dtype=int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [ ]:
np.full((4,4),7,dtype=int)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,24,25,dtype=int).reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.rand(5)

array([0.99850723, 0.99688385, 0.8626647 , 0.36776633, 0.22402595])

array([0.78575817, 0.09299267, 0.121068  , 0.28568964, 0.0792684 ])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.randn(5,5)

array([[ 0.06057122,  0.46162017, -0.40325231,  0.04732601, -0.29207316],
       [-0.01040755,  0.95812358,  1.85366968, -0.27028635,  0.48284851],
       [-1.69038803, -2.99688919,  0.20597813,  0.30091291,  0.71797485],
       [-1.00414606,  0.47635015, -1.66363727,  0.29168965,  0.40708228],
       [ 1.01189217, -0.60453396,  0.61373184,  1.97422685,  1.31874525]])

array([[-0.12359297, -0.91855618,  0.06455212, -2.27978204, -0.57486938],
       [-0.03804323, -0.5023371 , -0.44778236,  0.02017062, -1.92901903],
       [ 0.74789688, -0.24360289,  0.90076669,  1.04575783,  1.90222802],
       [ 0.57019415, -0.80369326, -0.05748809, -1.78616493, -0.82091478],
       [ 1.58482679, -0.1411782 , -1.04009651, -1.18600914, -0.54872206]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,51,size=(3,4))

array([[25, 21, 38, 41],
       [23, 28, 36, 38],
       [26, 28, 21, 36]])

array([[34, 23, 41, 29],
       [37, 47, 45, 49],
       [37, 25, 44, 29]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr = np.random.randint(0, 60, 48)
ranarr

array([33, 41, 19, 34, 56, 33, 38, 46, 38, 49, 57,  2, 23, 31, 52, 36, 40,
       50, 13,  7,  1, 17, 13, 44, 30, 22, 19, 53, 46, 56,  5, 47, 23,  0,
        4, 46, 52, 31, 10,  3, 11,  7, 43, 47, 53, 32,  8, 12])

In [ ]:
ranarr = ranarr.reshape(6,8)
ranarr

array([[33, 41, 19, 34, 56, 33, 38, 46],
       [38, 49, 57,  2, 23, 31, 52, 36],
       [40, 50, 13,  7,  1, 17, 13, 44],
       [30, 22, 19, 53, 46, 56,  5, 47],
       [23,  0,  4, 46, 52, 31, 10,  3],
       [11,  7, 43, 47, 53, 32,  8, 12]])

In [ ]:
ranarr.resize((6,8))
ranarr

array([[33, 41, 19, 34, 56, 33, 38, 46],
       [38, 49, 57,  2, 23, 31, 52, 36],
       [40, 50, 13,  7,  1, 17, 13, 44],
       [30, 22, 19, 53, 46, 56,  5, 47],
       [23,  0,  4, 46, 52, 31, 10,  3],
       [11,  7, 43, 47, 53, 32,  8, 12]])

array([[31, 17, 58,  3, 11, 19, 12, 35],
       [28, 18, 52, 24, 41, 40, 14, 56],
       [48,  8, 15,  7, 45,  3,  1, 56],
       [40, 53, 13, 29, 33,  2, 45, 46],
       [53, 19, 33, 21, 37, 52, 41, 25],
       [54, 52,  3,  7, 36, 30, 37, 42]])

In [ ]:
ranarr.reshape(-1)

array([33, 41, 19, 34, 56, 33, 38, 46, 38, 49, 57,  2, 23, 31, 52, 36, 40,
       50, 13,  7,  1, 17, 13, 44, 30, 22, 19, 53, 46, 56,  5, 47, 23,  0,
        4, 46, 52, 31, 10,  3, 11,  7, 43, 47, 53, 32,  8, 12])

In [ ]:
#reshape with -1

array([[31, 17, 58,  3, 11, 19, 12, 35],
       [28, 18, 52, 24, 41, 40, 14, 56],
       [48,  8, 15,  7, 45,  3,  1, 56],
       [40, 53, 13, 29, 33,  2, 45, 46],
       [53, 19, 33, 21, 37, 52, 41, 25],
       [54, 52,  3,  7, 36, 30, 37, 42]])

## Numpy Indexing and Selection

In [ ]:
test = np.arange(1,17).reshape(4,4)
test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#Create array below

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
test[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
test[:,0]

array([ 1,  5,  9, 13])

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
test[1,::2]

array([5, 7])

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
test[:,2] = 77
test

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [ ]:
test[[1,3],[0,2]]

array([ 5, 77])

array([ 5, 77])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
test[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above

In [ ]:
test[test>12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
test[test<10]

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
sum_1 = test[test<10] + test[test>12]

array([1, 2, 4, 5, 6, 8, 9])

array([77, 77, 77, 13, 14, 77, 16])

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
sum_1.std()

29.700546274093877

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
sum(test[:,1])

32

In [ ]:
test

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
#print array here

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

32

#### 23. Get the median,mean and std of 3rd column from array above

In [ ]:
test = np.arange(1,17).reshape(4,4)
test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
print(np.median(test[:,2]))
print(np.mean(test[:,2]))
print(np.std(test[:,2]))

9.0
9.0
4.47213595499958

In [ ]:
# !!! Probably the question asks the 3rd row for the values median, mean and std instead of 3rd column
test[:,2]

array([ 3,  7, 11, 15])

In [ ]:
np.median(test[2])

10.5

In [ ]:
np.mean(test[2])

10.5

In [ ]:
np.std(test[2])

1.118033988749895

#### 23. Get the median,mean and std of 3rd column from array above

In [ ]:
test = np.arange(1,17).reshape(4,4)
test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#median

10.5

In [ ]:
#mean

10.5

In [ ]:
#std

1.118033988749895

# Pandas Section

In [2]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [3]:
pd.read_csv("Salaries.csv")

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Status
count,148654.000000,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000,0.0,0.0
mean,74327.500000,66325.448841,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643,NaN,NaN
std,42912.857795,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538,NaN,NaN
min,1.000000,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000,NaN,NaN
25%,37164.250000,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000,NaN,NaN
50%,74327.500000,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000,NaN,NaN
75%,111490.750000,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000,NaN,NaN
max,148654.000000,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000,NaN,NaN

**How many different year value are there**

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [ ]:
#max

567595.43

In [ ]:
#avg

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

69489

**How much does ALBERT PARDINI make (including benefits)?**

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

LEGISLATION CLERK                    1
Sheriff                              1
MATERIALS AND SUPPLIES SUPERVISOR    1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

20366

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

,Id,EmployeeName,JobTitle,TotalPay,TotalPayBenefits
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43,567595.43
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),538909.28,538909.28
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91,335279.91
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61,332343.61
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19,326373.19
...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00
148650,148651,Not provided,Not provided,0.00,0.00
148651,148652,Not provided,Not provided,0.00,0.00
148652,148653,Not provided,Not provided,0.00,0.00
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13,-618.13

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**

,EmployeeName,JobTitle,TotalPay,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43,567595.43
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),538909.28,538909.28
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91,335279.91
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61,332343.61
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19,326373.19
...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00
148650,Not provided,Not provided,0.00,0.00
148651,Not provided,Not provided,0.00,0.00
148652,Not provided,Not provided,0.00,0.00
148653,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13,-618.13

**Print out the names of the employees who earn more than min, but less than avg**

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object